services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker_data/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker_data/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: samplepass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: hogehogedb
    hostname: postgres
    user: root

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: sample@sample.com
      PGADMIN_DEFAULT_PASSWORD: samplepass
    volumes:
      - ./docker_data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
